# Generated by Django 4.0.3 on 2022-05-25 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standings_slug', models.SlugField(null=True, unique=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('logo', models.ImageField(null=True, upload_to='media')),
                ('club', models.CharField(max_length=200)),
                ('MP', models.IntegerField()),
                ('GD', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('stadium', models.CharField(default='Ethiad', max_length=200)),
                ('stadium_img', models.ImageField(null=True, upload_to='media')),
                ('founded', models.IntegerField(null=True)),
                ('manager', models.CharField(max_length=200, null=True)),
                ('website', models.URLField(null=True)),
                ('text', models.TextField(null=True)),
                ('fact_one', models.CharField(max_length=500, null=True)),
                ('fact_two', models.CharField(max_length=500, null=True)),
                ('fact_three', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(100)])),
                ('tags', models.ManyToManyField(to='premier.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='premier.post')),
            ],
        ),
    ]
